drop table Viewing_Sets;
drop table FoodOrders;
drop table Registers;
drop table Administrator;
drop table Stay_In;
drop table Checks;
drop table Drugs_Prescribes;
drop table Health_Status_Check;
drop table Doctor_R2;
drop table Doctor;
drop table Room;
drop table Animal;
drop table Animal_R2;
drop table Customer;
drop table Customer_R2;
drop table Customer_R1;
commit;